import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginButton'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Link from 'next/link'
import { User } from 'next-auth';

export interface ISession {
  user?: User & {
    name: string;
    email: string;
    image: string;
  };
}


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{
  const session:ISession|null = await getServerSession(authOptions)
  return (
    <html lang="en">

      <body className={inter.className}>
      <div className='navbar'> 
        <Link href='/'> Home</Link>
        <Link href='/list'> List</Link>
        <LoginBtn session={session}></LoginBtn>
      </div>
        {children}
      </body>
    </html>
  )
}
